[library.qmvu13p]
location = .
sync-uri = .
sync-type = local
auto-sync = true

[library.spiny]
location = fusesoc_libraries/spiny
sync-uri = https://github.com/craigjb/spiny
sync-type = git
auto-sync = true

